language: php

sudo: required
addons:
  apt:
    packages:
      - libevent-dev
      - gdb
      - php5-dbg
      - php5-dev

php:
  - 5.5
  - 5.6

compiler:
  - gcc

install:
  - ulimit -c

before_script:
  - sudo apt-get remove apport
  - ulimit -c unlimited -S
  - bin/build.php --system
  - bin/build.php --phpize --clean --make
  - bin/build.php --info
  - composer install

# Run tests
script: php -dextension=./src/modules/ion.so vendor/bin/phpunit

after_failure:
 # If the program returned an error code, now we check for a
 # core file in the current working directory and dump the backtrace out
 - for i in $(find ./ -maxdepth 2 -name 'core*' -print); do gdb php core* -ex "thread apply all bt" -ex "set pagination 0" -batch; done;
