language: php

sudo: false

addons:
  apt:
    packages:
      - gdb
      - make
      - lcov

php:
#  - 7.1
  - 7.2

notifications:
  email:
    on_failure: change

os:
  - linux

env:
  matrix:
    - USE_ZEND_ALLOC=0
    - USE_ZEND_ALLOC=1

# Build extenstion and load phpunit + another deps
before_script:
  - composer global install phpion/ionizer
  - gem install coveralls-lcov
  - vendor/bin/ion info
#  - bin/ionizer.php --system --prepare --make --coverage --debug
  - vendor/bin/ion build . --prepare --make --coverage --debug
  - vendor/bin/ion desc .
  - composer install --quiet

# Run tests
script: vendor/bin/ion --debug test .
#script: bin/ionizer.php --test --gdb

# Send code coverage
after_success:
  # capture coverage info
  - lcov --directory . --capture --output-file coverage.info
  # filter out system and test code
  - lcov --remove coverage.info '*/src/deps/*' '*/ION/Stream/*' '*.h' --output-file coverage.info
  # debug before upload
  - lcov --list coverage.info
  # uploads to coveralls
  - coveralls-lcov coverage.info