language: php

sudo: false
addons:
  apt:
    packages:
      - libevent-dev
      - gdb
      - make
      - php5-dbg
      - php5-dev
      - lcov

php:
  - 7.0
#  - 5.5
#  - 5.6


os:
  - linux
#  - osx
#
#matrix:
#  allow_failures:
#    - os: osx


before_script:
  - gem install coveralls-lcov
  - bin/build.php --system --phpize --clean --make --coverage
  - bin/build.php --info
  - composer install

# Run tests
script: bin/build.php --test --use-gdb

# Send code coverage
after_success:
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info 'src/externals/*' '/usr/*' '/opt/*' '*/Zend/*' --output-file coverage.info # filter out system and test code
  - lcov --list coverage.info # debug before upload
  - coveralls-lcov coverage.info # uploads to coveralls