language: php

php:
    - 5.4
    - 5.5
    - 5.6

before_script:
    - sudo apt-get install libevent-dev
    - bin/build.php --phpize --clean --make
    - bin/build.php --info
    - composer install

# Run tests
script: bin/build.php --test