language: php

sudo: false
addons:
  apt:
    packages:
      - libevent-dev
      - gdb
      - make
#      - php7-dbg
#      - php7-dev
      - lcov

php:
  - 7.0

notifications:
    email:
       on_failure: change

os:
  - linux

env:
    matrix:
      - USE_ZEND_ALLOC=0
      - USE_ZEND_ALLOC=1


before_script:
  - gem install coveralls-lcov
  - bin/build.php --system --phpize --clean --make --coverage
  - bin/build.php --info
  - composer install

# Run tests
script: bin/build.php --test --use-gdb

# Send code coverage
after_success:
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info 'src/externals/*' '/usr/*' '/opt/*' '*/Zend/*' --output-file coverage.info # filter out system and test code
  - lcov --list coverage.info # debug before upload
  - coveralls-lcov coverage.info # uploads to coveralls