language: php

sudo: false
addons:
  apt:
    packages:
      - libevent-dev
      - gdb
      - make
      - lcov
      - ca-certificates

php:
  - 7.0

notifications:
  email:
    on_failure: change

os:
  - linux

env:
  matrix:
    - USE_ZEND_ALLOC=0
    - USE_ZEND_ALLOC=1

# Build extenstion and load phpunit + another deps
before_script:
  - gem install coveralls-lcov
  - bin/ionizer.php --system --phpize --clean --make --coverage
  - bin/ionizer.php --info
  - composer install --quiet

# Run tests
script: bin/ionizer.php --test --gdb

# Send code coverage
after_success:
  # capture coverage info
  - lcov --directory . --capture --output-file coverage.info
  # filter out system and test code
  - lcov --remove coverage.info '*/src/deps/*' '/usr/*' '/opt/*' '*/Zend/*' 'classes/*.h' '*/ION/Stream/*' '*.h' --output-file coverage.info
  # debug before upload
  - lcov --list coverage.info
  # uploads to coveralls
  - coveralls-lcov coverage.info