language: php

sudo: false
addons:
  apt:
    packages:
      - libevent-dev
      - gdb
      - php5-dbg

php:
  - 5.5
  - 5.6

compiler:
  - gcc

install:
  - ulimit -c

before_script:
  - ulimit -c unlimited -S
  - bin/build.php --phpize --clean --make
  - bin/build.php --info
  - php `which phpunit` --help
  - composer install

# Run tests
script: php -dextension=/Volumes/Data/Dev/php-ion/src/modules/ion.so vendor/bin/phpunit

after_failure:
 # If the program returned an error code, now we check for a
 # core file in the current working directory and dump the backtrace out
 - for i in $(find ./ -maxdepth 2 -name 'core*' -print); do gdb $(pwd)/test core* -ex "thread apply all bt" -ex "set pagination 0" -batch; done;
