language: php

sudo: false
addons:
  apt:
    packages:
      - libevent-dev
      - gdb
      - php5-dbg
      - php5-dev

php:
  - 5.5
  - 5.6

before_script:
  - bin/build.php --system --phpize --clean --make
  - bin/build.php --info
  - composer install

# Run tests
script: bin/build.php --test=tests/cases/IONTest.php --use-gdb

# Send code coverage
after_success:
  - cd src; gcov $(find . -iname '*.gcda')
  - cd src; gcov $(find . -iname '*.c')
  - bin/build.php --gcov-fix
  - find src -iname '*.gcda'
  - cd src; gcov $(find . -iname '*.gcda')
  - cd src; gcov $(find . -iname '*.c')
  - bin/gcov_to_clover.py --exclude src/externals --exclude /opt/local/include --exclude /usr/include -o clover.xml $(find . -iname "*.gcov")
  - php vendor/bin/coveralls