language: php

sudo: false
addons:
  apt:
    packages:
      - libevent-dev
      - gdb
      - php5-dbg
      - php5-dev

php:
  - 5.5
  - 5.6

before_script:
  - gem install rubysl-securerandom
  - gem install coveralls-gcov
  - bin/build.php --system --phpize --clean --make
  - bin/build.php --info
  - composer install

# Run tests
script: bin/build.php --test --use-gdb

after_success:
  - coveralls-gcov send --exclude src/externals