language: php

sudo: false
addons:
  apt:
    packages:
      - libevent-dev
      - gdb
      - php5-dbg
      - php5-dev

php:
  - 5.5
  - 5.6

before_script:
  - bin/build.php --system
  - bin/build.php --phpize --clean --make
  - bin/build.php --info
  - composer install --no-dev

# Run tests
script: 'ION_PHPUNIT_EXEC=`command -v phpunit` bin/build.php --test'